source 'https://github.com/CocoaPods/Specs.git'

target 'ARPopScrollController', :exclusive => true do
  pod "ARPopScrollController", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "ARPopScrollController", :path => "../"

  
end
